version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ai-toolkit-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama:/root/.ollama
    restart: unless-stopped
    networks:
      - ai-toolkit-network
    env_file:
      - ./config/ollama/.env

  postgres:
    image: postgres:16-alpine
    container_name: ai-toolkit-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    networks:
      - ai-toolkit-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: ai-toolkit-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant:/qdrant/storage
      - ./config/qdrant/config.yml:/qdrant/config/config.yml
    restart: unless-stopped
    networks:
      - ai-toolkit-network

  n8n:
    image: n8nio/n8n:latest
    container_name: ai-toolkit-n8n
    ports:
      - "5678:5678"
    volumes:
      - ./data/n8n:/home/node/.n8n
    restart: unless-stopped
    env_file:
      - ./config/n8n/.env
    depends_on:
      - postgres
    networks:
      - ai-toolkit-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ai-toolkit-ngrok
    command: start --config=/etc/ngrok/ngrok.yml n8n
    volumes:
      - ./config/ngrok/ngrok.yml:/etc/ngrok/ngrok.yml
    restart: unless-stopped
    depends_on:
      - n8n
    networks:
      - ai-toolkit-network

networks:
  ai-toolkit-network:
    driver: bridge
